### PR TITLE
Update pterodactyl.php

### PR DESCRIPTION
**Pull request by patricknasci**
Use password Generated by whmcs

### CODE REVIEW

**Comment by LeCodeCo** [comment]
Accounts are only made if the user doesn't already have an account on Pterodactyl already, rather than per service.

**Comment by patricknasci** [comment]
so what is the default password that is created for each user?

**Comment by patricknasci** [comment]
> Accounts are only made if the user doesn't already have an account on Pterodactyl already, rather than per service.
the account duplication does not happen, the email stays the same, it only updates the password.

**Comment by TrixterTheTux** [comment]
The user gets an email from Pterodactyl with a link to set up his password. The password isn't set intentionally for a couple of reasons:
1. The service password field isn't designed for users as every other service will have the wrong password/no effect on the user's password, causing confusion for the module's users and customers.
2. The password would be in plaintext for no good reason.
3. It's impossible (and a bad idea) to track the service password, causing it to be wrong at some point if we assume that the user has only a single service for the first time.

**Comment by patricknasci** [comment]
I can add a function where it checks if it has a service already added on the same client and it adds the password of the previous service to the new service.
so all services will be synchronized with the same username and password (being one account only).

**EXEMPLE TO SAVE CUSTOM USERNAME AND PASSWORD WHMCS :**
`$params['model']->serviceProperties->save(['Username' => $userPrefix . '_' . $params['clientsdetails']['id'], 'Password' => $params['password']]);`

**Comment by TrixterTheTux** [comment]
There's still no point in storing and displaying that information as it just reduces security for no benefit.

**Comment by patricknasci** [comment]
To add password reset function
using https://deploys.io/docs/api/pterodactyl/v1/#edit-user

is need to save the information so the user can even change the password via the whmcs client area in the future.

**Comment by TrixterTheTux** [comment]
That API endpoint doesn't depend on the previous password and if it did all my other points still stand - you're not gonna be able to track the password. Storing the changed password in WHMCS is also a big no due to the possibility of a security risk.

**Comment by patricknasci** [comment]
ok, then add the code when creating user:
 $params['model']->serviceProperties->save(['Username' => '', 'Password' => '']);`

It will delete the blank username and password whmcs field.

**Comment by TrixterTheTux** [comment]
Closing this in favor of https://github.com/pterodactyl/whmcs/commit/d9bf97c29096a59a91069772699007e9b0479c7e.

**Pull request closed without merging**
